# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Japan has over 50,000 vending machines, which sell everything from soda and snacks to clothes and eggs.
# Japan has four distinct seasons and is famous for its cherry blossom trees, which bloom in spring.
# The Japanese language has three different writing systems: kanji (Chinese characters), hiragana, and katakana.
# Sumo wrestling is Japan's national sport, and matches are held in a sacred ring called a dohyo. The wrestlers, who are called rikishi, must be at least 18 years old and weigh over 200 pounds.",
# The Great Wall of China is the longest wall in the world, stretching over 13,000 miles.
# China is home to the giant panda, which is a national symbol and is found only in China.
# China has the world's oldest continuous civilization, with a history that dates back over 4,000 years.
# The Chinese invented paper, the compass, and gunpowder.",

puts "start Seed"

country_data = [
  {
    name: "Japan",
    capital: "Tokyo",
    language: "Japanese",
    flag:
      "https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/1200px-Flag_of_Japan.svg.png",
    continent: "Asia",
    fun_fact:
      "Japan has the world's highest life expectancy, with the average Japanese person living to be over 84 years old.",
  },
  {
    name: "China",
    capital: "Beijing",
    language: "Mandarin",
    flag: "https://cdn.britannica.com/90/7490-004-BAD4AA72/Flag-China.jpg",
    continent: "Asia",
    fun_fact:
      "China has the world's largest population, with over 1.4 billion people.",
  },
  {
    name: "United States",
    capital: "Washington, D.C.",
    language: "English",
    flag:
      "https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/1200px-Flag_of_the_United_States.svg.png",
    continent: "North America",
    fun_fact:
      "
    The United States is home to many famous landmarks, including the Grand Canyon, Niagara Falls, and the Golden Gate Bridge.",
  },
  {
    name: "Mexico",
    capital: "Mexico City",
    language: "Spanish",
    flag: "https://cdn.britannica.com/73/2573-004-29818847/Flag-Mexico.jpg",
    continent: "North America",
    fun_fact: "The official name of Mexico is the United Mexican States.",
  },
  {
    name: "India",
    capital: "New Delhi",
    language: "Hindi",
    flag:
      "https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/1200px-Flag_of_India.svg.png",
    continent: "Asia",
    fun_fact: "ere",
  },
  {
    name: "Russia",
    capital: "Moscow",
    language: "Russian",
    flag:
      "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/640px-Flag_of_Russia.svg.png",
    continent: "Europe and Asia",
    fun_fact: "rer",
  },
  {
    name: "Germany",
    capital: "Berlin",
    language: "German",
    flag:
      "https://upload.wikimedia.org/wikipedia/en/thumb/b/ba/Flag_of_Germany.svg/1200px-Flag_of_Germany.svg.png",
    continent: "Europe",
    fun_fact: "rer",
  },
  {
    name: "France",
    capital: "Paris",
    language: "French",
    flag: "https://cdn.britannica.com/82/682-004-F0B47FCB/Flag-France.jpg",
    continent: "Europe",
    fun_fact: "rer",
  },
  {
    name: "Brazil",
    capital: "BrasÃ­lia",
    language: "Portuguese",
    flag:
      "https://upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/640px-Flag_of_Brazil.svg.png",
    continent: "South America",
    fun_fact: "rer",
  },
  {
    name: "Canada",
    capital: "Ottawa",
    language: "English",
    flag:
      "https://upload.wikimedia.org/wikipedia/en/thumb/c/cf/Flag_of_Canada.svg/1280px-Flag_of_Canada.svg.png",
    continent: "North America",
    fun_fact: "er",
  },
  {
    name: "Australia",
    capital: "Canberra",
    language: "English",
    flag: "https://cdn.britannica.com/78/6078-004-77AF7322/Flag-Australia.jpg",
    continent: "Australia",
    fun_fact: "re",
  },
  {
    name: "South Africa",
    capital: "Pretoria",
    language: "Afrikaans",
    flag:
      "https://cdn.britannica.com/27/4227-004-32423B42/Flag-South-Africa.jpg",
    continent: "Africa",
    fun_fact: "ere",
  },
  {
    name: "Kenya",
    capital: "Nairobi",
    language: "Swahili",
    flag: "https://cdn.britannica.com/15/15-004-B5D6BF80/Flag-Kenya.jpg",
    continent: "Africa",
    fun_fact: "er",
  },
  {
    name: "Indonesia",
    capital: "Jakarta",
    language: "Indonesian",
    flag: "https://cdn.britannica.com/48/1648-004-A33B72D8/Flag-Indonesia.jpg",
    continent: "Asia",
    fun_fact: "erer",
  },
  {
    name: "Iran",
    capital: "Tehran",
    language: "Persian",
    flag: "https://cdn.britannica.com/22/1722-004-EAD033D8/Flag-Iran.jpg",
    continent: "Asia",
    fun_fact: "erer",
  },
  {
    name: "Italy",
    capital: "Rome",
    language: "Italian",
    flag:
      "https://upload.wikimedia.org/wikipedia/en/thumb/0/03/Flag_of_Italy.svg/255px-Flag_of_Italy.svg.png",
    continent: "Europe",
    fun_fact: "erer",
  },
  {
    name: "Egypt",
    capital: "Cairo",
    language: "Arabic",
    flag: "https://cdn.britannica.com/85/185-004-1EA59040/Flag-Egypt.jpg",
    continent: "Africa and Asia",
    fun_fact: "erer",
  },
  {
    name: "Nigeria",
    capital: "Abuja",
    language: "English",
    flag: "https://cdn.britannica.com/68/5068-004-72A3F250/Flag-Nigeria.jpg",
    continent: "Africa",
    fun_fact: "erer",
  },
  {
    name: "Colombia",
    capital: "Bogotá",
    language: "Spanish",
    flag:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/255px-Flag_of_Colombia.svg.png",
    continent: "South America",
    fun_fact: "erer",
  },
  {
    name: "Argentina",
    capital: "Buenos Aires",
    language: "Spanish",
    flag: "https://cdn.britannica.com/69/5869-004-7D75CD05/Flag-Argentina.jpg",
    continent: "South America",
    fun_fact: "erer",
  },
  {
    name: "Pakistan",
    capital: "Islamabad",
    language: "Urdu",
    flag:
      "https://cdn.britannica.com/46/3346-004-D3BDE016/flag-symbolism-Pakistan-design-Islamic.jpg",
    continent: "Asia",
    fun_fact: "erer",
  },
  {
    name: "Thailand",
    capital: "Bangkok",
    language: "Thai",
    flag: "https://cdn.britannica.com/38/4038-004-111388C2/Flag-Thailand.jpg",
    continent: "Asia",
    fun_fact: "erer",
  },
  {
    name: "Vietnam",
    capital: "Hanoi",
    language: "Vietnamese",
    flag: "https://cdn.britannica.com/41/4041-004-D051B135/Flag-Vietnam.jpg",
    continent: "Asia",
    fun_fact: "erer",
  },
  {
    name: "Spain",
    capital: "Madrid",
    language: "Spanish",
    flag:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Bandera_de_Espa%C3%B1a.svg/1200px-Bandera_de_Espa%C3%B1a.svg.png",
    continent: "Europe",
    fun_fact: "erer",
  },
  {
    name: "Turkey",
    capital: "Ankara",
    language: "Turkish",
    flag:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/800px-Flag_of_Turkey.svg.png",
    continent: "Asia",
    fun_fact: "erer",
  },
  {
    name: "Philippines",
    capital: "Manila",
    language: "Filipino",
    flag:
      "https://cdn.britannica.com/73/3473-004-6E573BFA/Flag-Philippines.jpg",
    continent: "Asia",
    fun_fact: "erer",
  },
  {
    name: "Poland",
    capital: "Warsaw",
    language: "Polish",
    flag:
      "https://upload.wikimedia.org/wikipedia/en/thumb/1/12/Flag_of_Poland.svg/1200px-Flag_of_Poland.svg.png",
    continent: "Europe",
    fun_fact: "erer",
  },
  {
    name: "Greece",
    capital: "Athens",
    language: "Greek",
    flag: "https://cdn.britannica.com/49/1049-004-AE4BAD3E/Flag-Greece.jpg",
    continent: "Europe",
    fun_fact: "erer",
  },
  {
    name: "South Korea",
    capital: "Seoul",
    language: "Korean",
    flag:
      "https://cdn.britannica.com/49/1949-004-8818300C/Flag-South-Korea.jpg",
    continent: "Asia",
    fun_fact: "erer",
  },
  {
    name: "United Kingdom",
    capital: "London",
    language: "English",
    flag:
      "https://upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/800px-Flag_of_the_United_Kingdom.svg.png",
    continent: "Europe",
    fun_fact: "erer",
  },
  {
    name: "Guatemala",
    capital: "Guatemala City",
    language: "Spanish",
    flag:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Flag_of_Guatemala.svg/1200px-Flag_of_Guatemala.svg.png",
    continent: "North America",
    fun_fact: "erer",
  },
  {
    name: "Peru",
    capital: "Lima",
    language: "Spanish",
    flag:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Flag_of_Peru.svg/1200px-Flag_of_Peru.svg.png",
    continent: "South America",
    fun_fact: "erer",
  },
  {
    name: "Honduras",
    capital: "Tegucigalpa",
    language: "Spanish",
    flag:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Flag_of_Honduras.svg/1200px-Flag_of_Honduras.svg.png",
    continent: "North America",
    fun_fact: "erer",
  },
  {
    name: "Ecuador",
    capital: "Quito",
    language: "Spanish",
    flag:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Flag_of_Ecuador.svg/1200px-Flag_of_Ecuador.svg.png",
    continent: "South America",
    fun_fact: "erer",
  },
  {
    name: "Ethiopia",
    capital: "Addis Ababa",
    language: "Amharic",
    flag: "https://www.countryflags.io/et/flat/64.png",
    continent: "Africa",
    fun_fact: "erer",
  },
  {
    name: "Cuba",
    capital: "Havana",
    language: "Spanish",
    flag: "https://www.countryflags.io/cu/flat/64.png",
    continent: "North America",
    fun_fact: "erer",
  },
  {
    name: "Chile",
    capital: "Santiago",
    language: "Spanish",
    flag: "https://www.countryflags.io/cl/flat/64.png",
    continent: "South America",
    fun_fact: "erer",
  },
  {
    name: "Bolivia",
    capital: "La Paz",
    language: "Spanish",
    flag: "https://www.countryflags.io/bo/flat/64.png",
    continent: "South America",
    fun_fact: "erer",
  },
  {
    name: "Zambia",
    capital: "Lusaka",
    language: "English",
    flag: "https://www.countryflags.io/zm/flat/64.png",
    continent: "Africa",
    fun_fact: "erer",
  },
  {
    name: "Yemen",
    capital: "Sana'a",
    language: "Arabic",
    flag: "https://www.countryflags.io/ye/flat/64.png",
    continent: "Asia",
    fun_fact: "erer",
  },
  {
    name: "Sweden",
    capital: "Stockholm",
    language: "Swedish",
    flag: "https://www.countryflags.io/se/flat/64.png",
    continent: "Europe",
    fun_fact: "erer",
  },
  {
    name: "Tunisia",
    capital: "Tunis",
    language: "Arabic",
    flag: "https://www.countryflags.io/tn/flat/64.png",
    continent: "Africa",
    fun_fact: "erer",
  },
  {
    name: "Lebanon",
    capital: "Beirut",
    language: "Arabic",
    flag: "https://www.countryflags.io/lb/flat/64.png",
    continent: "Asia",
    fun_fact: "erer",
  },
  {
    name: "Nepal",
    capital: "Kathmandu",
    language: "Nepali",
    flag: "https://www.countryflags.io/np/flat/64.png",
    continent: "Asia",
    fun_fact: "erer",
  },
  {
    name: "Panama",
    capital: "Panama City",
    language: "Spanish",
    flag: "https://www.countryflags.io/pa/flat/64.png",
    continent: "North America",
    fun_fact: "erer",
  },
  {
    name: "Jordan",
    capital: "Amman",
    language: "Arabic",
    flag: "https://www.countryflags.io/jo/flat/64.png",
    continent: "Asia",
    fun_fact: "erer",
  },
  {
    name: "Sudan",
    capital: "Khartoum",
    language: "Arabic",
    flag:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Sudan.svg/1200px-Flag_of_Sudan.svg.png",
    continent: "Africa",
    fun_fact: "erer",
  },
  {
    name: "Uganda",
    capital: "Kampala",
    language: "English",
    flag:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Flag_of_Uganda.svg/1200px-Flag_of_Uganda.svg.png",
    continent: "Africa",
    fun_fact: "erer",
  },
  {
    name: "Tanzania",
    capital: "Dodoma",
    language: "Swahili",
    flag:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Tanzania.svg/1200px-Flag_of_Tanzania.svg.png",
    continent: "Africa",
    fun_fact: "erer",
  },
  {
    name: "Albania",
    capital: "Tirana",
    language: "Albanian",
    flag: "https://flagpedia.net/data/flags/normal/al.png",
    continent: "Europe",
    fun_fact: "erer",
  },
  {
    name: "Belarus",
    capital: "Minsk",
    language: "Belarusian",
    flag: "https://flagpedia.net/data/flags/normal/by.png",
    continent: "Europe",
    fun_fact: "erer",
  },
  {
    name: "Cambodia",
    capital: "Phnom Penh",
    language: "Khmer",
    flag: "https://flagpedia.net/data/flags/normal/kh.png",
    continent: "Asia",
    fun_fact: "erer",
  },
  {
    name: "Denmark",
    capital: "Copenhagen",
    language: "Danish",
    flag: "https://flagpedia.net/data/flags/normal/dk.png",
    continent: "Europe",
    fun_fact: "erer",
  },
  {
    name: "El Salvador",
    capital: "San Salvador",
    language: "Spanish",
    flag: "https://flagpedia.net/data/flags/normal/sv.png",
    continent: "North America",
    fun_fact: "erer",
  },
  {
    name: "Finland",
    capital: "Helsinki",
    language: "Finnish",
    flag: "https://flagpedia.net/data/flags/normal/fi.png",
    continent: "Europe",
    fun_fact: "erer",
  },
  {
    name: "Guinea",
    capital: "Conakry",
    language: "French",
    flag: "https://flagpedia.net/data/flags/normal/gn.png",
    continent: "Africa",
    fun_fact: "erer",
  },
  {
    name: "Namibia",
    capital: "Windhoek",
    language: "English",
    flag:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Namibia.svg/1200px-Flag_of_Namibia.svg.png",
    continent: "Africa",
    fun_fact: "erer",
  },
  {
    name: "Czech Republic",
    capital: "Prague",
    language: "Czech",
    flag: "https://flagpedia.net/data/flags/normal/cz.png",
    continent: "Europe",
    fun_fact: "erer",
  },
  {
    name: "Luxembourg",
    capital: "Luxembourg City",
    language: "Luxembourgish",
    flag: "https://flagpedia.net/data/flags/normal/lu.png",
    continent: "Europe",
    fun_fact: "erer",
  },
  {
    name: "Monaco",
    capital: "Monaco",
    language: "French",
    flag: "https://flagpedia.net/data/flags/normal/mc.png",
    continent: "Europe",
    fun_fact: "erer",
  },
  {
    name: "Botswana",
    capital: "Gaborone",
    language: "English",
    flag: "https://flagpedia.net/data/flags/normal/bw.png",
    continent: "Africa",
    fun_fact: "erer",
  },
  {
    name: "Mauritius",
    capital: "Port Louis",
    language: "English",
    flag: "https://flagpedia.net/data/flags/normal/mu.png",
    continent: "Africa",
    fun_fact: "erer",
  },
  {
    name: "Seychelles",
    capital: "Victoria",
    language: "French",
    flag: "https://flagpedia.net/data/flags/normal/sc.png",
    continent: "Africa",
    fun_fact: "erer",
  },
  {
    name: "Bhutan",
    capital: "Thimphu",
    language: "Dzongkha",
    flag: "https://flagpedia.net/data/flags/normal/bt.png",
    continent: "Asia",
    fun_fact: "erer",
  },
  {
    name: "Brunei",
    capital: "Bandar Seri Begawan",
    language: "Malay",
    flag: "https://flagpedia.net/data/flags/normal/bn.png",
    continent: "Asia",
    fun_fact: "erer",
  },
  {
    name: "Laos",
    capital: "Vientiane",
    language: "Lao",
    flag: "https://flagpedia.net/data/flags/normal/la.png",
    continent: "Asia",
    fun_fact: "erer",
  },
  {
    name: "Maldives",
    capital: "Malé",
    language: "Dhivehi",
    flag: "https://flagpedia.net/data/flags/normal/mv.png",
    continent: "Asia",
    fun_fact: "erer",
  },
  {
    name: "Armenia",
    capital: "Yerevan",
    language: "Armenian",
    flag: "https://flagpedia.net/data/flags/normal/am.png",
    continent: "Asia",
    fun_fact: "erer",
  },
  {
    name: "Azerbaijan",
    capital: "Baku",
    language: "Azerbaijani",
    flag: "https://flagpedia.net/data/flags/normal/az.png",
    continent: "Asia",
    fun_fact: "erer",
  },
  {
    name: "Belgium",
    capital: "Brussels",
    language: "Dutch, French, German",
    flag: "https://flagpedia.net/data/flags/normal/be.png",
    continent: "Europe",
    fun_fact: "erer",
  },
  {
    name: "Bulgaria",
    capital: "Sofia",
    language: "Bulgarian",
    flag: "https://flagpedia.net/data/flags/normal/bg.png",
    continent: "Europe",
    fun_fact: "erer",
  },
  {
    name: "Croatia",
    capital: "Zagreb",
    language: "Croatian",
    flag: "https://flagpedia.net/data/flags/normal/hr.png",
    continent: "Europe",
    fun_fact: "erer",
  },
  {
    name: "Cyprus",
    capital: "Nicosia",
    language: "Greek, Turkish",
    flag: "https://flagpedia.net/data/flags/normal/cy.png",
    continent: "Europe",
    fun_fact: "erer",
  },
  {
    name: "Estonia",
    capital: "Tallinn",
    language: "Estonian",
    flag: "https://flagpedia.net/data/flags/normal/ee.png",
    continent: "Europe",
    fun_fact: "erer",
  },
  {
    name: "Iceland",
    capital: "Reykjavik",
    language: "Icelandic",
    flag: "https://flagpedia.net/data/flags/normal/is.png",
    continent: "Europe",
    fun_fact: "erer",
  },
  {
    name: "Latvia",
    capital: "Riga",
    language: "Latvian",
    flag: "https://flagpedia.net/data/flags/normal/lv.png",
    continent: "Europe",
  },
  {
    name: "Moldova",
    capital: "Chisinau",
    language: "Moldovan",
    flag: "https://flagpedia.net/data/flags/normal/md.png",
    continent: "Europe",
    fun_fact: "erer",
  },
  {
    name: "Montenegro",
    capital: "Podgorica",
    language: "Montenegrin",
    flag: "https://flagpedia.net/data/flags/normal/me.png",
    continent: "Europe",
    fun_fact: "erer",
  },
  {
    name: "Norway",
    capital: "Oslo",
    language: "Norwegian",
    flag: "https://flagpedia.net/data/flags/normal/no.png",
    continent: "Europe",
    fun_fact: "erer",
  },
  {
    name: "Romania",
    capital: "Bucharest",
    language: "Romanian",
    flag: "https://flagpedia.net/data/flags/normal/ro.png",
    continent: "Europe",
    fun_fact: "erer",
  },
  {
    name: "Serbia",
    capital: "Belgrade",
    language: "Serbian",
    flag: "https://flagpedia.net/data/flags/normal/rs.png",
    continent: "Europe",
    fun_fact: "erer",
  },
  {
    name: "Slovakia",
    capital: "Bratislava",
    language: "Slovak",
    flag: "https://flagpedia.net/data/flags/normal/sk.png",
    continent: "Europe",
    fun_fact: "erer",
  },
  {
    name: "Slovenia",
    capital: "Ljubljana",
    language: "Slovenian",
    flag: "https://flagpedia.net/data/flags/normal/si.png",
    continent: "Europe",
    fun_fact: "erer",
  },
  {
    name: "Switzerland",
    capital: "Bern",
    language: "German, French, Italian, Romansh",
    flag: "https://flagpedia.net/data/flags/normal/ch.png",
    continent: "Europe",
    fun_fact: "erer",
  },
  {
    name: "Taiwan",
    capital: "Taipei",
    language: "Mandarin Chinese",
    flag: "https://flagpedia.net/data/flags/normal/tw.png",
    continent: "Asia",
    fun_fact: "erer",
  },
  {
    name: "Tajikistan",
    capital: "Dushanbe",
    language: "Tajik",
    flag: "https://flagpedia.net/data/flags/normal/tj.png",
    continent: "Asia",
    fun_fact: "erer",
  },
  {
    name: "Turkmenistan",
    capital: "Ashgabat",
    language: "Turkmen",
    flag: "https://flagpedia.net/data/flags/normal/tm.png",
    continent: "Asia",
    fun_fact: "erer",
  },
  {
    name: "Algeria",
    capital: "Algiers",
    language: "Arabic",
    flag: "https://flagpedia.net/data/flags/normal/dz.png",
    continent: "Africa",
    fun_fact: "erer",
  },
  {
    name: "Angola",
    capital: "Luanda",
    language: "Portuguese",
    flag: "https://flagpedia.net/data/flags/normal/ao.png",
    continent: "Africa",
    fun_fact: "erer",
  },
  {
    name: "Benin",
    capital: "Porto-Novo",
    language: "French",
    flag: "https://flagpedia.net/data/flags/normal/bj.png",
    continent: "Africa",
    fun_fact: "erer",
  },
  {
    name: "Botswana",
    capital: "Gaborone",
    language: "English",
    flag: "https://flagpedia.net/data/flags/normal/bw.png",
    continent: "Africa",
    fun_fact: "erer",
  },
  {
    name: "Burkina Faso",
    capital: "Ouagadougou",
    language: "French",
    flag: "https://flagpedia.net/data/flags/normal/bf.png",
    continent: "Africa",
    fun_fact: "erer",
  },
  {
    name: "Burundi",
    capital: "Bujumbura",
    language: "Kirundi, French",
    flag: "https://flagpedia.net/data/flags/normal/bi.png",
    continent: "Africa",
    fun_fact: "erer",
  },
  {
    name: "Cameroon",
    capital: "Yaoundé",
    language: "French, English",
    flag: "https://flagpedia.net/data/flags/normal/cm.png",
    continent: "Africa",
    fun_fact: "erer",
  },
  {
    name: "Cape Verde",
    capital: "Praia",
    language: "Portuguese",
    flag: "https://flagpedia.net/data/flags/normal/cv.png",
    continent: "Africa",
    fun_fact: "erer",
  },
  {
    name: "Central African Republic",
    capital: "Bangui",
    language: "French",
    flag: "https://flagpedia.net/data/flags/normal/cf.png",
    continent: "Africa",
    fun_fact: "erer",
  },
  {
    name: "Chad",
    capital: "N'Djamena",
    language: "Arabic, French",
    flag: "https://flagpedia.net/data/flags/normal/td.png",
    continent: "Africa",
    fun_fact: "erer",
  },
  {
    name: "Comoros",
    capital: "Moroni",
    language: "Arabic, French",
    flag: "https://flagpedia.net/data/flags/normal/km.png",
    continent: "Africa",
    fun_fact: "erer",
  },
  {
    name: "Congo (Brazzaville)",
    capital: "Brazzaville",
    language: "French",
    flag: "https://flagpedia.net/data/flags/normal/cg.png",
    continent: "Africa",
    fun_fact: "erer",
  },
  {
    name: "Congo (Kinshasa)",
    capital: "Kinshasa",
    language: "French",
    flag: "https://flagpedia.net/data/flags/normal/cd.png",
    continent: "Africa",
    fun_fact: "erer",
  },
  {
    name: "Djibouti",
    capital: "Djibouti",
    language: "Arabic, French",
    flag: "https://flagpedia.net/data/flags/normal/dj.png",
    continent: "Africa",
    fun_fact: "erer",
  },
  {
    name: "Equatorial Guinea",
    capital: "Malabo",
    language: "Spanish, French, Portuguese",
    flag: "https://flagpedia.net/data/flags/normal/gq.png",
    continent: "Africa",
    fun_fact: "erer",
  },
  {
    name: "Eritrea",
    capital: "Asmara",
    language: "Tigrinya, Arabic, English",
    flag: "https://flagpedia.net/data/flags/normal/er.png",
    continent: "Africa",
    fun_fact: "erer",
  },
  {
    name: "Ghana",
    capital: "Accra",
    language: "English",
    flag:
      "https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Ghana.svg",
    continent: "Africa",
    fun_fact: "erer",
  },
  {
    name: "Venezuela",
    capital: "Caracas",
    language: "Spanish",
    flag:
      "https://upload.wikimedia.org/wikipedia/commons/0/06/Flag_of_Venezuela.svg",
    continent: "South America",
    fun_fact: "erer",
  },
  {
    name: "Costa Rica",
    capital: "San Jose",
    language: "Spanish",
    flag:
      "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Costa_Rica.svg",
    continent: "North America",
    fun_fact: "erer",
  },
  {
    name: "Uruguay",
    capital: "Montevideo",
    language: "Spanish",
    flag:
      "https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Uruguay.svg",
    continent: "South America",
    fun_fact: "erer",
  },
]
country_data.each do |country|
  Country.create(
    name: country[:name],
    capital: country[:capital],
    language: country[:language],
    flag: country[:flag],
    continent: country[:continent],
    fun_fact: country[:fun_fact],
  )
end

puts "Done"
